CREATE TABLE authors
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    email_address VARCHAR(255),
    CONSTRAINT pk_authors PRIMARY KEY (id)
);

CREATE TABLE book_author
(
    author_id BIGINT NOT NULL,
    book_id   BIGINT NOT NULL
);

CREATE TABLE book_genre
(
    book_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL
);

CREATE TABLE books
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(250)                            NOT NULL,
    isbn         VARCHAR(20),
    publish_year INT                                     NOT NULL,
    publisher    VARCHAR(100),
    edition      VARCHAR(20),
    pages        INT                                     NOT NULL,
    CONSTRAINT pk_books PRIMARY KEY (id)
);

CREATE TABLE genres
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_author FOREIGN KEY (author_id) REFERENCES authors (id);

ALTER TABLE book_author
    ADD CONSTRAINT fk_booaut_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_genre
    ADD CONSTRAINT fk_boogen_on_book FOREIGN KEY (book_id) REFERENCES books (id);

ALTER TABLE book_genre
    ADD CONSTRAINT fk_boogen_on_genre FOREIGN KEY (genre_id) REFERENCES genres (id);